
[font]
size = 14.8 # recommended increments are 3.7, 7.4, 11.1, 14.8

[font.normal]
family = "DepartureMono Nerd Font"
style = "Regular"

[window]
dimensions = { columns = 120, lines = 55 }
position = { x = 1512, y = 490 }
decorations = "buttonless"  # Clean look without title bar buttons
opacity = 0.95
blur = true  # Nice translucency effect on macOS

[scrolling]
history = 50000  # Generous scroll-back buffer
multiplier = 2   # Faster scrolling

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
